Адаптивные сетки
htmlacademy-adaptive/1423269-pink-20 pull request #6
Opened 2020-08-19 08:31 UTC by masolemia

2020-08-19 21:16 UTC, costigans requested changes
При именовании файлов избегай пробелов и кириллицы.

2020-08-19 21:16 UTC, costigans commented on source/form.html
> +            <img class="page-footer__logo--desktop" src="img/logo-pink-blue-desktop.svg" width="147" height="40" alt="Pink">
Кстати, ты снова используешь модификатор без блока/элемента :(

2020-08-19 21:16 UTC, costigans commented on source/index.html
>          <section class="description">
Кажется, что сейчас название не подходит для этого блока.
Это не просто «описание», этот блок знакомит с возможностями приложения.

2020-08-19 21:16 UTC, costigans commented on source/index.html
> +              </div>
Это отдельный блок, который мало связан с «возможностями». Придумай ему логичное название, и модификаторы на заголовок и текст не придётся использовать :)

2020-08-19 21:16 UTC, costigans commented on source/less/utils/variables.less
> +@desktop-width:1000px;
Почему для десктопа выбрала ширину в 1000 пикселей?

2020-08-19 21:16 UTC, costigans commented on source/less/utils/variables.less
> +@desktop-width:1000px;
Путаница в именах переменных

2020-08-19 21:16 UTC, costigans commented on source/less/utils/global.less
> +}
Эти привила для блока «page» и они должны быть в соответствующем файле

2020-08-19 21:16 UTC, costigans commented on source/less/utils/global.less
>  }
Не в своёи файле

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/panorama.less
> +}
Можешь смело удалять, эти правила тебе не пригодятся

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/page-main.less
> +  background-image: url("../../img/iphone-hand-mobile@1x.png");
Ошибка в адресе изображения.
Проверь во всех файлах

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/page-main.less
> +    padding: 80px 20px;
Не хватает пустой строки

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/page-footer.less
> +  }
Удали все подобные «модификаторы», они не нужны

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/main-nav.less
> +  padding-top: 25px;
Размеры отступов не соответствуют макету

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/main-nav.less
> +    left: 544px;
Не проще использовать `right`?

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/main-nav.less
> +    background-color: transparent;
Зачем?

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/download-app.less
> +    .size (300px;55px);
Пробел не на месте

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/description.less
> +    width: 252px;
Не нужна ширина для этого текста

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/description.less
> +    width: 310px;
Не нужна ширина

2020-08-19 21:16 UTC, costigans commented on source/less/blocks/description.less
> +    text-align: start;
Не подходящее значение свойства

2020-08-23 23:36 UTC, costigans requested changes
Кажется образовалась какая-то путница в разметке?
Можем разобрать это задание в скайпе

2020-08-23 23:36 UTC, costigans commented on source/index.html
> +        <div class="page-main__tablet">
Почему этот элемент вдруг стал tablet?

2020-08-23 23:36 UTC, costigans commented on source/index.html
> +            <section class="download-app">
Этот section начинается раньше — на 35 строке.
Тогда `download-app` можно использовать просто как div, и h2 будет не нужен

2020-08-23 23:36 UTC, costigans commented on source/index.html
> +              <div class="page__container">
По остальным (tablet, desktop) макетам этот контейнер выглядит лишним

2020-08-23 23:36 UTC, costigans commented on source/index.html
> +              <div class="capabilities__block-tablet">
Откуда опять tablet?)

2020-08-23 23:36 UTC, costigans commented on source/index.html
> +              <img src="img/icon-timer.svg" width="238px" height="276px" alt="24 часа">
Это исключительно декоративное изображение — сделать фоном

2020-08-23 23:36 UTC, costigans commented on source/index.html
> +                <div class="page-main__img">
Зачем h1 вкладывать в элемент img?

2020-08-23 23:36 UTC, costigans commented on source/less/utils/variables.less
> +@desktop-width:1200px;
Верни как было, я просто задал вопрос, чтобы убедиться, что ты понимаешь, что делаешь :)

2020-08-23 23:36 UTC, costigans commented on source/less/blocks/page.less
> +.page-header {
Если это блок `page-header`, то ему место в отдельном файле.
Если это элемент `page__header`, то он неверно написан.

2020-08-23 23:36 UTC, costigans commented on source/less/blocks/page-main.less
>      background-image: url("../../img/bg-back-tablet@1x.jpg");
Неверный адрес изображения

2020-08-23 23:36 UTC, costigans commented on source/less/blocks/page-main.less
>    .page-main__block {
Ты уверена, что их нужно объединять?

2020-08-23 23:36 UTC, costigans commented on source/less/blocks/main-nav.less
> +    padding-bottom: 48px;
Слишком большие отступы для мобильной версии

2020-08-23 23:36 UTC, costigans commented on source/less/blocks/main-nav.less
> +    left: 544px;
Потому что в прииицпе не совсем подходящая реализация. Разберём в скайпе.

2020-08-24 18:03 UTC, masolemia commented on source/index.html
> +        <div class="page-main__tablet">
потому что он объединяет блоки и актуален начиная с планшетной версии

2020-08-24 18:04 UTC, masolemia commented on source/index.html
> +            <section class="download-app">
нет, это же разные блоки (по крайней мере для мобильной версии)
1. вводная ко всей странице
2. секция со скачиванием приложения
Див на 35 строке нужен для объединения их на одном фоне в планшетной и десктопной версии

2020-08-24 18:08 UTC, masolemia commented on source/index.html
> +              <div class="capabilities__block-tablet">
Наверное, надо объяснить, почему я использую несколько контейнеров 
первый основной контейнер (74 строка) нужен для фона
а следующий определяет сетку в планшетной и десктопной версии (устанавливает флексы)
если убрать один из них - или у нас фон будет ограничен page__container или флексы будут в ужасном виде

2020-08-24 18:09 UTC, masolemia commented on source/index.html
> +                <div class="page-main__img">
потому что там была картинка

2020-08-24 18:22 UTC, masolemia commented on source/less/blocks/page-main.less
>      background-image: url("../../img/bg-back-tablet@1x.jpg");
переписала, но странно - у меня открывается

2020-08-24 18:25 UTC, masolemia commented on source/less/blocks/page-main.less
>    .page-main__block {
Да, это нужно только для указания фона 
block - у всех страниц одно изображение
tablet - только на первой странице в планшетной и десктопной версии 
P.S. Я пытаюсь сказать, что эти свойства не повредят ничему другому, даже если что-то изменится

2020-08-24 18:26 UTC, masolemia commented on source/less/blocks/main-nav.less
> +    padding-bottom: 48px;
так это же для десктопной версии

2020-08-25 15:23 UTC, costigans commented on source/less/blocks/page-main.less
>      background-image: url("../../img/bg-back-tablet@1x.jpg");
Сборка на локальной машине и на проде (гитхаб) отличается по доступам к каталогам.

2020-08-25 15:23 UTC, costigans commented on source/less/blocks/page-main.less
>    .page-main__block {
Вот, этот блок tablet отдельно для планшета/десктопа меня как раз сильно смущает

2020-08-25 15:23 UTC, costigans commented on source/index.html
> +                <div class="page-main__img">
Ну и что, что остаётся фоном? Сам элемент же не является никаким изображением.

2020-08-25 15:23 UTC, costigans commented on source/index.html
> +        <div class="page-main__tablet">
Где-то тут определённо ошибка

2020-08-25 15:23 UTC, costigans commented on source/less/blocks/main-nav.less
> +    padding-bottom: 48px;
Строка 43-43. 
Я придрался к отступам на мобильной версии, потому что они и правда странно выглядят — https://i.imgur.com/rhvYCuf.png

Как думаешь, почему так произошло?

2020-08-27 03:47 UTC, costigans requested changes

2020-08-27 03:47 UTC, costigans commented on source/index.html
> +              <div class="download-app__tablet">
Почему tablet остался?)

2020-08-27 03:47 UTC, costigans commented on source/less/blocks/header-block.less
> +      background-repeat: no-repeat;
Ненужное дублирование свойства

2020-08-27 03:47 UTC, costigans commented on source/less/blocks/photos.less
> +    padding-top: 100px;
А зачем повторять? У тебя это свойство от tablet-width применяется.

2020-08-27 03:47 UTC, costigans commented on source/less/blocks/photos.less
> +    padding-top: 100px;
Так же как и .font

2020-08-27 03:47 UTC, costigans commented on source/less/blocks/prices.less
> +    background-image: url("../../img/bg-hit.png");
Поправь путь

2020-08-27 07:59 UTC, merged